### ISSUE TITLE
Client secrets in the wild

### ISSUE THREAD

**Issue by Nioub** [DidiBear/flask-graphql-oauth#1]
Hi!

You should NOT give your own client secrets :
- https://github.com/DidiBear/flask-graphql-oauth/blob/master/auth.py#L19
- https://github.com/DidiBear/flask-graphql-oauth/blob/master/auth.py#L23

Best regards,

**Comment by didibear** [comment]
Thanks ! I am removing and invalidating them ASAP. I will use env variables instead.

**Comment by didibear** [comment]
Fixed with the latest commit => https://github.com/DidiBear/flask-graphql-oauth/commit/7af95c6073905ca20b1b49cd6daf6efb7ce67200
